version: '3'

services:
  ssh:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    restart: always
    labels: { autoheal: true } # work with willfarrell/autoheal
    healthcheck:
      # "--connect-timeout", "2"
      test: ["CMD", "curl", "-fI", "-x", "socks5h://127.0.0.1:${SOCKS5_Port}", "https://www.google.com"]
      start_period: 3s
      interval: 10s
      timeout: 2s
      retries: 3
    network_mode: host
    user: "${USER_UID}:${USER_GID}"
    container_name: ${APP_Name}-ssh
    volumes:
    - ./configs/:/app/configs:ro
    # - ./logs/:/app/logs
    environment: ["TZ=Asia/Shanghai"]
    working_dir: /app
    command:
    - ./target/main
    - ssh
    - -config=configs/prod.yaml
    - -addr=:${SOCKS5_Port}
