version: '3'

services:
  ssh:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    labels: { autoheal: true }
    restart: always
    healthcheck:
      # "--connect-timeout", "2"
      test: ["CMD", "curl", "-fI", "-x", "socks5h://127.0.0.1:${SOCKS5_Port}", "https://www.google.com"]
      start_period: 3s
      interval: 10s
      timeout: 2s
      retries: 3
    container_name: ${APP_Name}-ssh
    user: "${USER_UID}:${USER_GID}"
    network_mode: host
    #networks: ["net"]
    #ports: ["127.0.0.1:${SOCKS5_Port}:${SOCKS5_Port}"]
    environment: ["TZ=Asia/Shanghai"]
    working_dir: /app
    volumes:
    - ./configs/:/app/configs:ro
    # - ./logs/:/app/logs
    command:
    - ./target/main
    - ssh
    - -config=configs/prod.yaml
    - -addr=:${SOCKS5_Port}

#networks:
#  net: { name: "local", driver: bridge, external: false }
