version: '3'

services:
  ${APP_Name}:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    restart: always
    labels: { autoheal: true } # work with willfarrell/autoheal
    healthcheck:
      # --connect-timeout 2 --fail
      test: ["CMD", "curl", "-X", "OPTIONS", "-I", "-x", "socks5h://127.0.0.1:${SOCKS5_Port}", "https://www.google.com"]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 2
    network_mode: host
    user: "${USER_UID}:${USER_GID}"
    container_name: ${APP_Name}-ssh
    volumes:
    - ./configs/:/app/configs:ro
    working_dir: /app
    environment: ["TZ=Asia/Shanghai"]
    command: [./target/main, ssh, -config=configs/prod.yaml, -addr=:${SOCKS5_Port}]
    # Remove the user section when using socks5_proxy.sh 
    # command: [./target/socks5_proxy.sh, remote_host, :${SOCKS5_Port}]
