app_name: socks5-proxy
app_version: 1.0.0
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]
repository: git@github.com:d2jvkpn/socks5-proxy.git

ssh_config: |
  ##### location: configs/local.yaml

  ssh:
    ssh_address: remote_host:22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts
    socks5_user: hello
    socks5_password: world

  noauth:
    ssh_address: remote_host:22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts
