app_name: socks5-proxy
app_version: 1.0.1
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]
repository: git@github.com:d2jvkpn/socks5-proxy.git
image_name: socks5-proxy

ssh_proxy: |
  ##### location: configs/local.yaml

  ssh:
    ssh_address: remote_host:22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts
    socks5_user: hello
    socks5_password: world

  noauth:
    ssh_address: remote_host:22
    ssh_user: account
    ssh_password: password
    ssh_private_key: /home/account/.ssh/id_rsa
    ssh_known_hosts: /home/account/.ssh/known_hosts

socks5_proxy: |
    ##### location: configs/ssh.conf

    Host remote_host
        # ProxyJump another_host
        HostName 127.0.0.1
        User account
        Port 22
        # IdentityFile ~/.ssh/id_rsa
        IdentityFile configs/ssh.key
        # UserKnownHostsFile ~/.ssh/known_hosts
        UserKnownHostsFile configs/known_hosts
        Compression yes
        LogLevel INFO
        ServerAliveInterval 5
        ServerAliveCountMax 3
        ExitOnForwardFailure yes

proxy_pac: |
  // location: proxy.pac

  function FindProxyForURL(url, host) {
    if (isPlainHostName(host) || shExpMatch(host, "*.local")) {
      return "DIRECT";
    }

    if (shExpMatch(host, "*.a.example.com")) {
      return "PROXY proxy.example.com:8080";
    } else if (shExpMatch(host, "*.b.example.com")) {
      return "PROXY proxy1.example.com:8080; PROXY proxy2.example.com:8080";
    } else if (shExpMatch(host, "*.c.example.com")) {
      return "PROXY proxy3.example.com:8080; DIRECT";
    }

    return "DIRECT";
  }
