socks5_ssh:
  ssh_address: localhost:22
  ssh_user: account
  ssh_password: password
  #ssh_private_key: /home/account/.ssh/id_rsa
  ssh_known_hosts: /home/account/.ssh/known_hosts
  socks5_user: hello
  socks5_password: world
